version: '3.8'

services:
  mysql:
    container_name: beersp-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=beersp_db
      - MYSQL_USER=maolro
      - MYSQL_PASSWORD=beersp_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_beersp:/docker-entrypoint-initdb.d 
    networks:
      - my_network

volumes:
  mysql_data:
  
networks:
  my_network:
    driver: bridge