version: '3.8'

services:
  mysql:
    container_name: beersp-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=beersp_db
      - MYSQL_USER=maolro
      - MYSQL_PASSWORD=beersp_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_beersp:/docker-entrypoint-initdb.d 
    networks:
      - my_network

  backend:
    build: .  # Construye la imagen usando el Dockerfile en este directorio
    container_name: beersp-api
    ports:
      - "8000:8000" 
    volumes:
      - ./app:/app/app 
    environment:
      # Pasa la URL de la BDD al contenedor
      - DATABASE_URL=mysql+pymysql://maolro:beersp_db@mysql:3306/beersp_db
    networks:
      - my_network
    depends_on:
      - mysql #

volumes:
  mysql_data:
  app:

networks:
  my_network:
    driver: bridge